"""Functional tests for the Milestone 2 sitemap + robots.txt endpoints.

Milestone 2 added @astrojs/sitemap and a public/robots.txt referencing the
sitemap. These are HTTP-level assertions against the running preview server:

    /sitemap-index.xml — must serve 200, point at /sitemap-0.xml
    /sitemap-0.xml     — must serve 200 and list all six .html URLs
                         (the .html suffix is the URL-preservation contract;
                         astro.config.mjs `serialize()` exists exactly to keep
                         this true)
    /robots.txt        — must serve 200 and reference the sitemap-index.xml

Run against the preview server brought up by the lifecycle `run` script
(http://127.0.0.1:4321).
"""
from __future__ import annotations

import pytest
import requests

BASE_URL = "http://127.0.0.1:4321"
TIMEOUT = 10

# The six pretty-URL paths whose .html-suffixed canonical entries must appear
# in sitemap-0.xml. The contract is that the integration's serialize() patch
# keeps the .html — losing the suffix would break inbound links and search
# engine continuity.
SITEMAP_HTML_URLS = [
    "https://lafrenchtechdenver.com/index.html",
    "https://lafrenchtechdenver.com/about.html",
    "https://lafrenchtechdenver.com/companies-sponsors.html",
    "https://lafrenchtechdenver.com/events.html",
    "https://lafrenchtechdenver.com/members-benefits.html",
    "https://lafrenchtechdenver.com/resources.html",
]


@pytest.fixture(autouse=True)
def preview_server_up():
    """Confirm the Astro preview server is reachable before every test."""
    resp = requests.get(f"{BASE_URL}/", timeout=TIMEOUT)
    assert resp.status_code == 200, (
        f"Expected preview server at {BASE_URL} to respond 200, "
        f"got {resp.status_code}. Did the lifecycle `run` step start it?"
    )


class TestSitemapIndex:
    """`/sitemap-index.xml` is generated by @astrojs/sitemap into dist/."""

    def test_sitemap_index_responds_200(self):
        resp = requests.get(f"{BASE_URL}/sitemap-index.xml", timeout=TIMEOUT)
        assert resp.status_code == 200, (
            f"GET /sitemap-index.xml -> {resp.status_code}; expected 200"
        )

    def test_sitemap_index_is_xml(self):
        resp = requests.get(f"{BASE_URL}/sitemap-index.xml", timeout=TIMEOUT)
        assert resp.status_code == 200
        ct = resp.headers.get("content-type", "")
        assert "xml" in ct.lower(), (
            f"sitemap-index.xml served with non-xml content-type: {ct!r}"
        )

    def test_sitemap_index_points_at_sitemap_0(self):
        resp = requests.get(f"{BASE_URL}/sitemap-index.xml", timeout=TIMEOUT)
        body = resp.text
        assert "<sitemapindex" in body, "sitemap-index.xml missing <sitemapindex> root"
        assert "https://lafrenchtechdenver.com/sitemap-0.xml" in body, (
            "sitemap-index.xml does not reference /sitemap-0.xml at the canonical site URL"
        )


class TestSitemap0:
    """`/sitemap-0.xml` lists every page in src/pages/ with the .html suffix."""

    @pytest.fixture(scope="class")
    def body(self):
        resp = requests.get(f"{BASE_URL}/sitemap-0.xml", timeout=TIMEOUT)
        assert resp.status_code == 200
        return resp.text

    def test_sitemap_0_responds_200(self):
        resp = requests.get(f"{BASE_URL}/sitemap-0.xml", timeout=TIMEOUT)
        assert resp.status_code == 200, (
            f"GET /sitemap-0.xml -> {resp.status_code}; expected 200"
        )

    def test_sitemap_0_is_urlset(self, body):
        assert "<urlset" in body, "sitemap-0.xml missing <urlset> root"

    @pytest.mark.parametrize("html_url", SITEMAP_HTML_URLS)
    def test_sitemap_lists_html_url(self, body, html_url):
        # Every page must appear with the .html suffix preserved — see
        # astro.config.mjs `serialize()`.
        assert f"<loc>{html_url}</loc>" in body, (
            f"sitemap-0.xml is missing canonical .html URL {html_url!r}; "
            f"check that astro.config.mjs serialize() runs"
        )

    def test_sitemap_does_not_emit_pretty_urls(self, body):
        # Pretty URLs (no .html) are the regression we explicitly guard against:
        # they would break the URL-preservation contract.
        bad_urls = [
            "<loc>https://lafrenchtechdenver.com/about</loc>",
            "<loc>https://lafrenchtechdenver.com/companies-sponsors</loc>",
            "<loc>https://lafrenchtechdenver.com/events</loc>",
            "<loc>https://lafrenchtechdenver.com/members-benefits</loc>",
            "<loc>https://lafrenchtechdenver.com/resources</loc>",
        ]
        for bad in bad_urls:
            assert bad not in body, (
                f"sitemap-0.xml emitted pretty URL {bad!r}; "
                f"the .html suffix has been dropped — astro.config.mjs serialize() is broken"
            )

    def test_sitemap_root_uses_index_html(self, body):
        # The root entry must surface as /index.html, not bare /.
        assert "<loc>https://lafrenchtechdenver.com/</loc>" not in body, (
            "sitemap-0.xml emitted bare / for root; serialize() should rewrite "
            "it to /index.html"
        )


class TestRobotsTxt:
    """`public/robots.txt` is copied verbatim into dist/."""

    def test_robots_responds_200(self):
        resp = requests.get(f"{BASE_URL}/robots.txt", timeout=TIMEOUT)
        assert resp.status_code == 200, (
            f"GET /robots.txt -> {resp.status_code}; expected 200"
        )

    def test_robots_allows_all(self):
        resp = requests.get(f"{BASE_URL}/robots.txt", timeout=TIMEOUT)
        body = resp.text
        assert "User-agent: *" in body, "robots.txt missing 'User-agent: *' line"
        assert "Allow: /" in body, "robots.txt missing 'Allow: /' line"

    def test_robots_references_sitemap(self):
        resp = requests.get(f"{BASE_URL}/robots.txt", timeout=TIMEOUT)
        body = resp.text
        assert "Sitemap: https://lafrenchtechdenver.com/sitemap-index.xml" in body, (
            "robots.txt does not reference the production sitemap-index.xml URL"
        )
