"""Foundation milestone: SEO + GitHub Pages contract tests.

Three artifacts emitted by the build that must work at the HTTP level:

  /sitemap-index.xml   - generated by @astrojs/sitemap, must point at /sitemap-0.xml
  /sitemap-0.xml       - lists all six page URLs with the .html suffix preserved
                         (serialize() override in astro.config.mjs)
  /robots.txt          - copied verbatim from public/, references the sitemap
  /CNAME               - copied verbatim from public/CNAME, contains the apex
                         domain so GitHub Pages keeps the custom domain attached

Run against the preview server brought up by lifecycle `run`
(http://127.0.0.1:4321).
"""
from __future__ import annotations

import pytest
import requests

BASE_URL = "http://127.0.0.1:4321"
TIMEOUT = 10

SITEMAP_HTML_URLS = [
    "https://lafrenchtechdenver.com/index.html",
    "https://lafrenchtechdenver.com/about.html",
    "https://lafrenchtechdenver.com/companies-sponsors.html",
    "https://lafrenchtechdenver.com/events.html",
    "https://lafrenchtechdenver.com/members-benefits.html",
    "https://lafrenchtechdenver.com/resources.html",
]


@pytest.fixture(autouse=True)
def preview_server_up():
    resp = requests.get(f"{BASE_URL}/", timeout=TIMEOUT)
    assert resp.status_code == 200, (
        f"Expected preview server at {BASE_URL} to respond 200, "
        f"got {resp.status_code}. Did the lifecycle `run` step start it?"
    )


class TestSitemapIndex:
    """`/sitemap-index.xml` is generated by @astrojs/sitemap into dist/."""

    def test_responds_200(self):
        resp = requests.get(f"{BASE_URL}/sitemap-index.xml", timeout=TIMEOUT)
        assert resp.status_code == 200, (
            f"GET /sitemap-index.xml -> {resp.status_code}; expected 200"
        )

    def test_is_xml(self):
        resp = requests.get(f"{BASE_URL}/sitemap-index.xml", timeout=TIMEOUT)
        ct = resp.headers.get("content-type", "")
        assert "xml" in ct.lower(), (
            f"sitemap-index.xml served with non-xml content-type: {ct!r}"
        )

    def test_points_at_sitemap_0(self):
        resp = requests.get(f"{BASE_URL}/sitemap-index.xml", timeout=TIMEOUT)
        body = resp.text
        assert "<sitemapindex" in body, "missing <sitemapindex> root"
        assert "https://lafrenchtechdenver.com/sitemap-0.xml" in body, (
            "sitemap-index.xml does not reference /sitemap-0.xml"
        )


class TestSitemap0:
    """`/sitemap-0.xml` lists every page with the .html suffix."""

    @pytest.fixture(scope="class")
    def body(self):
        resp = requests.get(f"{BASE_URL}/sitemap-0.xml", timeout=TIMEOUT)
        assert resp.status_code == 200
        return resp.text

    def test_responds_200(self):
        resp = requests.get(f"{BASE_URL}/sitemap-0.xml", timeout=TIMEOUT)
        assert resp.status_code == 200, (
            f"GET /sitemap-0.xml -> {resp.status_code}; expected 200"
        )

    def test_is_urlset(self, body):
        assert "<urlset" in body, "sitemap-0.xml missing <urlset> root"

    @pytest.mark.parametrize("html_url", SITEMAP_HTML_URLS)
    def test_lists_html_url(self, body, html_url):
        # Every page must appear with the .html suffix preserved — see
        # astro.config.mjs serialize() override.
        assert f"<loc>{html_url}</loc>" in body, (
            f"sitemap-0.xml is missing canonical .html URL {html_url!r}"
        )

    def test_does_not_emit_pretty_urls(self, body):
        # Pretty URLs (no .html) would break the URL-preservation contract.
        bad_urls = [
            "<loc>https://lafrenchtechdenver.com/about</loc>",
            "<loc>https://lafrenchtechdenver.com/companies-sponsors</loc>",
            "<loc>https://lafrenchtechdenver.com/events</loc>",
            "<loc>https://lafrenchtechdenver.com/members-benefits</loc>",
            "<loc>https://lafrenchtechdenver.com/resources</loc>",
        ]
        for bad in bad_urls:
            assert bad not in body, (
                f"sitemap-0.xml emitted pretty URL {bad!r}; "
                "the .html suffix has been dropped"
            )

    def test_no_bare_root_url(self, body):
        """Root entry must surface as /index.html, not bare /."""
        assert "<loc>https://lafrenchtechdenver.com/</loc>" not in body, (
            "sitemap-0.xml emitted bare / for root; "
            "serialize() should rewrite it to /index.html"
        )


class TestRobotsTxt:
    """`public/robots.txt` is copied verbatim into dist/."""

    def test_responds_200(self):
        resp = requests.get(f"{BASE_URL}/robots.txt", timeout=TIMEOUT)
        assert resp.status_code == 200

    def test_allows_all(self):
        resp = requests.get(f"{BASE_URL}/robots.txt", timeout=TIMEOUT)
        body = resp.text
        assert "User-agent: *" in body, "robots.txt missing 'User-agent: *' line"
        assert "Allow: /" in body, "robots.txt missing 'Allow: /' line"

    def test_references_sitemap(self):
        resp = requests.get(f"{BASE_URL}/robots.txt", timeout=TIMEOUT)
        body = resp.text
        assert "Sitemap: https://lafrenchtechdenver.com/sitemap-index.xml" in body, (
            "robots.txt does not reference the production sitemap-index.xml URL"
        )


class TestCnameContract:
    """`public/CNAME` must be served verbatim. GitHub Pages depends on this."""

    def test_responds_200(self):
        resp = requests.get(f"{BASE_URL}/CNAME", timeout=TIMEOUT)
        assert resp.status_code == 200, (
            f"GET /CNAME -> {resp.status_code}; "
            "GitHub Pages custom domain depends on this file"
        )

    def test_body_is_apex_domain(self):
        resp = requests.get(f"{BASE_URL}/CNAME", timeout=TIMEOUT)
        # Whitespace tolerance: trailing newline is fine, but the only payload
        # must be the apex domain.
        body = resp.text.strip()
        assert body == "lafrenchtechdenver.com", (
            f"/CNAME body was {body!r}, expected exactly 'lafrenchtechdenver.com'"
        )


class TestFavicon:
    """Favicon must be served (M1 ships favicon.ico via public/)."""

    def test_favicon_responds(self):
        resp = requests.get(f"{BASE_URL}/favicon.ico", timeout=TIMEOUT)
        # Some pipelines move it under /assets/ — accept either, but at least
        # one must work.
        if resp.status_code != 200:
            resp_assets = requests.get(
                f"{BASE_URL}/assets/favicon.ico", timeout=TIMEOUT
            )
            assert resp_assets.status_code == 200, (
                f"Neither /favicon.ico ({resp.status_code}) nor "
                f"/assets/favicon.ico ({resp_assets.status_code}) returns 200"
            )
